set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports UART_0_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_0_0_txd]
set_property PACKAGE_PIN J16 [get_ports UART_0_0_rxd]
set_property PACKAGE_PIN J17 [get_ports UART_0_0_txd]
set_property PACKAGE_PIN T21 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN T22 [get_ports {GPIO_0_0_tri_io[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[4]}]
set_property PACKAGE_PIN U22 [get_ports {GPIO_0_0_tri_io[2]}]
set_property PACKAGE_PIN U21 [get_ports {GPIO_0_0_tri_io[3]}]
set_property PACKAGE_PIN V22 [get_ports {GPIO_0_0_tri_io[4]}]
set_property PACKAGE_PIN W22 [get_ports {GPIO_0_0_tri_io[5]}]
set_property PACKAGE_PIN U19 [get_ports {GPIO_0_0_tri_io[6]}]
set_property PACKAGE_PIN U14 [get_ports {GPIO_0_0_tri_io[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports UART_1_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_1_txd]
set_property PACKAGE_PIN AA9 [get_ports UART_1_txd]
set_property PACKAGE_PIN Y10 [get_ports UART_1_rxd]

set_property IOSTANDARD LVCMOS33 [get_ports UART_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_0_txd]
set_property PACKAGE_PIN AA11 [get_ports UART_0_txd]
set_property PACKAGE_PIN Y11 [get_ports UART_0_rxd]

set_property IOSTANDARD LVCMOS33 [get_ports sin_0]
set_property IOSTANDARD LVCMOS33 [get_ports sout_0]

set_property IOSTANDARD LVCMOS33 [get_ports sin_2]
set_property IOSTANDARD LVCMOS33 [get_ports sout_2]
set_property IOSTANDARD LVCMOS33 [get_ports sin_1]
set_property IOSTANDARD LVCMOS33 [get_ports sout_1]
set_property IOSTANDARD LVCMOS33 [get_ports sin_4]
set_property IOSTANDARD LVCMOS33 [get_ports sout_4]
set_property IOSTANDARD LVCMOS33 [get_ports sin_7]
set_property IOSTANDARD LVCMOS33 [get_ports sout_7]
set_property IOSTANDARD LVCMOS33 [get_ports sin_8]
set_property IOSTANDARD LVCMOS33 [get_ports sout_8]
set_property IOSTANDARD LVCMOS33 [get_ports sin_3]
set_property IOSTANDARD LVCMOS33 [get_ports sout_3]
set_property IOSTANDARD LVCMOS33 [get_ports sin_5]
set_property IOSTANDARD LVCMOS33 [get_ports sout_5]
set_property IOSTANDARD LVCMOS33 [get_ports sin_6]
set_property IOSTANDARD LVCMOS33 [get_ports sout_6]
set_property IOSTANDARD LVCMOS33 [get_ports sin_9]
set_property IOSTANDARD LVCMOS33 [get_ports sout_9]
set_property PACKAGE_PIN AB11 [get_ports sin_0]
set_property PACKAGE_PIN Y11 [get_ports sout_0]
set_property PACKAGE_PIN W10 [get_ports sin_5]
set_property PACKAGE_PIN W11 [get_ports sout_5]
set_property PACKAGE_PIN V9 [get_ports sin_6]
set_property PACKAGE_PIN V10 [get_ports sout_6]
set_property PACKAGE_PIN T6 [get_ports sin_9]
set_property PACKAGE_PIN AB6 [get_ports sout_9]
set_property PACKAGE_PIN AA8 [get_ports sin_3]
set_property PACKAGE_PIN AA9 [get_ports sout_3]
set_property PACKAGE_PIN R6 [get_ports sin_8]
set_property PACKAGE_PIN AB7 [get_ports sout_8]
set_property PACKAGE_PIN V8 [get_ports sin_7]
set_property PACKAGE_PIN W8 [get_ports sout_7]
set_property PACKAGE_PIN V12 [get_ports sin_4]
set_property PACKAGE_PIN W12 [get_ports sout_4]
set_property PACKAGE_PIN AB10 [get_ports sin_1]
set_property PACKAGE_PIN AA11 [get_ports sout_1]
set_property PACKAGE_PIN AB9 [get_ports sin_2]
set_property PACKAGE_PIN Y10 [get_ports sout_2]

set_property IOSTANDARD LVCMOS33 [get_ports pwm_0]
set_property PACKAGE_PIN V7 [get_ports pwm_0]

set_property IOSTANDARD LVCMOS33 [get_ports capPWM_0]
set_property PACKAGE_PIN W7 [get_ports capPWM_0]

set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_sda_io]

set_property IOSTANDARD LVCMOS33 [get_ports IIC_1_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_1_sda_io]
set_property PACKAGE_PIN V5 [get_ports IIC_0_scl_io]
set_property PACKAGE_PIN V4 [get_ports IIC_0_sda_io]
set_property PACKAGE_PIN U6 [get_ports IIC_1_scl_io]
set_property PACKAGE_PIN U5 [get_ports IIC_1_sda_io]

