# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# XDC: new/top.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_250M_0/system_rst_ps7_0_250M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_250M_0 || ORIG_REF_NAME==system_rst_ps7_0_250M_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_uart16550_0_1/system_axi_uart16550_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uart16550_0_1 || ORIG_REF_NAME==system_axi_uart16550_0_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_uart16550_0_0/system_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uart16550_0_0 || ORIG_REF_NAME==system_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_uart16550_1_0/system_axi_uart16550_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uart16550_1_0 || ORIG_REF_NAME==system_axi_uart16550_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_uart16550_2_0/system_axi_uart16550_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uart16550_2_0 || ORIG_REF_NAME==system_axi_uart16550_2_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_uart16550_3_0/system_axi_uart16550_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uart16550_3_0 || ORIG_REF_NAME==system_axi_uart16550_3_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_uart16550_0_2/system_axi_uart16550_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uart16550_0_2 || ORIG_REF_NAME==system_axi_uart16550_0_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_uart16550_1_1/system_axi_uart16550_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uart16550_1_1 || ORIG_REF_NAME==system_axi_uart16550_1_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_uart16550_2_1/system_axi_uart16550_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uart16550_2_1 || ORIG_REF_NAME==system_axi_uart16550_2_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_uart16550_3_1/system_axi_uart16550_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uart16550_3_1 || ORIG_REF_NAME==system_axi_uart16550_3_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_uart16550_4_0/system_axi_uart16550_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uart16550_4_0 || ORIG_REF_NAME==system_axi_uart16550_4_0} -quiet] -quiet

# IP: bd/system/ip/system_PWM_0_0/system_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PWM_0_0 || ORIG_REF_NAME==system_PWM_0_0} -quiet] -quiet

# IP: bd/system/ip/system_CapturePWM_0_0/system_CapturePWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_CapturePWM_0_0 || ORIG_REF_NAME==system_CapturePWM_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/system_ooc.xdc
