# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/ZYNQ/ZED/ZED.cache/wt [current_project]
set_property parent.project_path F:/ZYNQ/ZED/ZED.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  f:/ZYNQ/ZED/userIP/CapturePWM_1.0
  f:/ZYNQ/ZED/userIP/PWM_1.0
} [current_project]
set_property ip_output_repo f:/ZYNQ/ZED/ZED.cache/ip [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib F:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/hdl/system_wrapper.v
add_files F:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_rst_ps7_0_250M_0/system_rst_ps7_0_250M_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_rst_ps7_0_250M_0/system_rst_ps7_0_250M_0.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_rst_ps7_0_250M_0/system_rst_ps7_0_250M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_0_1/system_axi_uart16550_0_1_board.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_0_1/system_axi_uart16550_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_0_1/system_axi_uart16550_0_1.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_0_0/system_axi_uart16550_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_0_0/system_axi_uart16550_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_0_0/system_axi_uart16550_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_1_0/system_axi_uart16550_1_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_1_0/system_axi_uart16550_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_1_0/system_axi_uart16550_1_0.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_2_0/system_axi_uart16550_2_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_2_0/system_axi_uart16550_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_2_0/system_axi_uart16550_2_0.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_3_0/system_axi_uart16550_3_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_3_0/system_axi_uart16550_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_3_0/system_axi_uart16550_3_0.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_0_2/system_axi_uart16550_0_2_board.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_0_2/system_axi_uart16550_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_0_2/system_axi_uart16550_0_2.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_1_1/system_axi_uart16550_1_1_board.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_1_1/system_axi_uart16550_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_1_1/system_axi_uart16550_1_1.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_2_1/system_axi_uart16550_2_1_board.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_2_1/system_axi_uart16550_2_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_2_1/system_axi_uart16550_2_1.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_3_1/system_axi_uart16550_3_1_board.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_3_1/system_axi_uart16550_3_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_3_1/system_axi_uart16550_3_1.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_4_0/system_axi_uart16550_4_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_4_0/system_axi_uart16550_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_axi_uart16550_4_0/system_axi_uart16550_4_0.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all F:/ZYNQ/ZED/ZED.srcs/sources_1/bd/system/system_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/ZYNQ/ZED/ZED.srcs/constrs_1/new/system.xdc
set_property used_in_implementation false [get_files F:/ZYNQ/ZED/ZED.srcs/constrs_1/new/system.xdc]

read_xdc F:/ZYNQ/ZED/ZED.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files F:/ZYNQ/ZED/ZED.srcs/constrs_1/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7z020clg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_wrapper.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb"
